server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: glomo

logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name:
    url:
    username:
    password:

---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: stg
---
spring:
  config:
    activate:
      on-profile: prd