name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.1.0
      with:
        args: -Dsonar.projectKey=my_project_key

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/glomo .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/glomo
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}